include:
  - template: Auto-DevOps.gitlab-ci.yml

variables:
  CI_DEPENDENCY_PROXY_SERVER: ''

build:
  image: 'registry.gitlab.com/gitlab-org/cluster-integration/auto-build-image:v1.49.0'
.auto-deploy:
  image: "registry.gitlab.com/gitlab-org/cluster-integration/auto-deploy-image:v2.64.0"
